Feat: TableCell atom and Table molecule
BancoBanQuito/front-banquito pull request #10
Opened 2023-01-17 22:27 UTC by listerineh

brief:
- Includes a TableCell atom
- Includes a Table molecule using TableCell atoms and data sent as props

2023-01-17 23:12 UTC, jlgalarza3 requested changes

2023-01-17 23:12 UTC, jlgalarza3 commented on src/components/molecules/TableMolecule.tsx
> +  borderRadius: '10px'
Hay una forma de aceptar childrens y no solo strings? Recuerda que hay tablas que tienen en su fila botones o componentes.

![image](https://user-images.githubusercontent.com/44406615/213032461-0247b3d5-f6b1-45c1-95fd-2106a75bae23.png)

2023-01-17 23:12 UTC, jlgalarza3 commented on src/components/atoms/TableCellAtom.tsx
> +  text: string,
Lo mismo, no siempre vamos a aceptar strings en las celdas

2023-01-18 04:13 UTC, listerineh commented on src/components/atoms/TableCellAtom.tsx
> +  text: string,
Done

2023-01-18 04:13 UTC, listerineh commented on src/components/molecules/TableMolecule.tsx
> +  borderRadius: '10px'
Done 👍

2023-01-18 15:42 UTC, merged