AF-53: Create screen checkbook payment
BancoBanQuito/front-banquito pull request #28
Opened 2023-01-21 15:45 UTC by SebastianAndrango

Describe: 
Create screen "checkbook payment" only user interface

2023-01-21 19:18 UTC, FranciscoDavidMunozArmas requested changes
Coloca SizeButton en lugar de Button

2023-01-22 02:47 UTC, listerineh approved these changes

2023-01-22 22:12 UTC, SebastianAndrango commented
Se realizó los cambios solicitados

2023-01-22 23:37 UTC, FranciscoDavidMunozArmas approved these changes

2023-01-22 23:37 UTC, merged