Create Atom: Checkbox
BancoBanQuito/front-banquito pull request #7
Opened 2023-01-17 21:33 UTC by jlgalarza3

2023-01-17 22:35 UTC, listerineh requested changes
solo ese pequeño cambio 💯

2023-01-17 22:35 UTC, listerineh commented on src/components/atoms/Checkbox.tsx
> +    </Box>
Recomiendo devolver elementos sin ningun layout, Eliminar el Box que lo contiene

2023-01-17 22:39 UTC, jlgalarza3 commented on src/components/atoms/Checkbox.tsx
> +    </Box>
Ok, hay alguna otra forma de enviar el label?

2023-01-17 23:03 UTC, jlgalarza3 commented on src/components/atoms/Checkbox.tsx
> +    </Box>
DONE

2023-01-18 14:43 UTC, listerineh approved these changes
GJ 💯

2023-01-18 14:43 UTC, merged